### ISSUE TITLE
I ❤ GCC

### ISSUE THREAD

**Issue by KevinZonda** [EpLiar/I-always-like#1]
Hi there! I LOVE GCC 4EVER!
And, is there a wedding photo of GCC and me?

**Comment by EpLiar** [comment]
> Hi there! I LOVE GCC 4EVER!
> And, is there a wedding photo of GCC and me?

ni bu dui jin

**Comment by KevinZonda** [comment]
oh, thank you!😁 we r all gcc's husbands

**Comment by ghost** [comment]
@KevinZonda 
Did you mean: `public shared class gcc` ?

**Comment by KevinZonda** [comment]
> @KevinZonda
> Did you mean: `public shared class gcc` ?

brilliant
